version: '3.3'
services:
  burr-detection:
    build: .
    runtime: nvidia
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
